'use strict';
const fs = require('node:fs'), path = require('node:path');
const root = path.join(__dirname,'..');
for (const [source,output,variable] of [
  ['panel.css','panel-style.js','LyricPilotStyles'],
  ['panel.html','panel-template.js','LyricPilotTemplate']
]) {
  const text = fs.readFileSync(path.join(root,'ui',source),'utf8');
  const result = `// Generated by scripts/build-ui.cjs. Edit ui/${source}.\nglobalThis.${variable} = ${JSON.stringify(text)};\n`;
  const destination = path.join(root,'extension',output);
  if (process.argv.includes('--check')) {
    if (fs.readFileSync(destination,'utf8') !== result) throw new Error(`${output} is stale; run npm run build:ui`);
  } else fs.writeFileSync(destination,result);
}
